name: Bygg og push db-datapopulator

on:
  push:
    branches:
      - master
    paths:
      - db-datapopulator/**

env:
  IMAGE: ghcr.io/${{ github.repository }}/db-datapopulator
  VERSION: latest

jobs:
  build-and-publish-on-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_PUSH_USERNAME }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}
      - name: Bygg, tag og push Docker image
        run: |
          docker build -t ${IMAGE}:${VERSION} db-datapopulator/.
          docker push ${IMAGE}
